---
- name: Configure RHEL 6 - Build node for dom4j version:1.6.1
  hosts: centos-6
  become: true

  vars:
    java:
      install_folder: /opt/java
      user: java

  roles:
    - role: install-jdk
    - role: install-ant
    - role: install-maven
    
  pre_tasks:
    # ==> Fix hosts file. Remove hostname from local loop. A workaround for vagrant
    # adding hostname to local loop
    - name: fix host file 127.0.0.1 entry
      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644
