---
- name: Configure RHEL 6 
  hosts: centos-6
  become: true

  vars:
    java:
      install_file: j2sdk-1_4_2_02-linux-i586.bin
      install_folder: /opt/java      

    dependencies:
      - libselinux-python 
      - glibc.i686  

    users:
      - java
      - dev

  tasks:
      - name: Install required dependencies
        yum:
          name: "{{item}}"
        loop: "{{dependencies}}"    

      - name: Ensure that required user exist
        user:
          name: "{{ item }}"
          state: present
        loop: "{{ users }}"   

      - name: Create Java install. folder
        file:    
          path: "{{ java.install_folder }}"
          state: directory
          owner: java
          group: java
          mode: 0755
          
      - name: Check if Java 1.4 was already installed - j*sdk* folder exists
        find:
          paths: "{{ java.install_folder }}"
          patterns: "j*sdk*"
          file_type: directory
        register: find_result

      - set_fact:
          java_installed: "{{ find_result.matched > 0 }}"
     
      - debug:
          msg: "Java already installed {{ java_installed }} "

      - name: Copy install. file to install folder
        copy:
          src: "files/{{ java.install_file }}"
          dest: "{{ java.install_folder }}"
          owner: java
          group: java
          mode: u+x
        register: result
        when: not java_installed

      - set_fact:
          install_from_file: "{{ result is not skipped}}" 

      - debug:
          msg: "Install Java from file {{ install_from_file }} "

      - name: Fix install file
        command:
          chdir: "{{ java.install_folder }}"
          cmd: "sed -i 's/tail +/tail -n +/g' {{ java.install_file }}"
        become: true
        become_user: java
        when: install_from_file

      - name: Set Agreement to 1/true
        lineinfile:
          path: "{{ java.install_folder }}/{{ java.install_file }}"
          regexp: "^agreed="
          line: "agreed=1"
        become: true
        become_user: java
        when: install_from_file

      - name: Remove more agreement section from install 
        command:
          chdir: "{{ java.install_folder }}"
          cmd: "sed -i 's/more <<\"EOF\"/cat <<\"EOF\"/g' {{ java.install_file }}"
        become: true
        become_user: java
        when: install_from_file

      - name: Run Java installer
        command:
          chdir: "{{ java.install_folder }}"
          cmd: "./{{ java.install_file }}" 
        become: true  
        become_user: java
        when: install_from_file

      - name: Remove install file
        file:
          path: "{{ java.install_folder }}/{{ java.install_file }}"
          state: absent
        when: install_from_file

      - name: Find where Java was installed
        find:
          paths: "{{ java.install_folder }}"
          patterns: "j*sdk*"
          file_type: directory
        register: find_result

      - debug:
          msg: "Java install. path {{ find_result.files[0].path }}" 

      - name: Set JAVA_HOME env. for user java
        lineinfile:
          path: ~/.bash_profile
          line: JAVA_HOME={{ find_result.files[0].path }} 
          regexp: "^JAVA_HOME="
          insertbefore: export PATH
        become: true
        become_user: java    

      - name: Set PATH env. for user 'java'
        lineinfile:
          path: ~/.bash_profile
          line: PATH=$PATH:$JAVA_HOME/bin
          state: present
          insertbefore: export PATH
        become: true
        become_user: java

  pre_tasks:
    # ==> Fix hosts file. Remove hostname from local loop. A workaround for vagrant
    # adding hostname to local loop
    - name: fix host file 127.0.0.1 entry
      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644
